version: '3.8'

services:
  server:
    container_name: tiny_gomail
    build:
      context: .
      dockerfile: Dockerfile.development
    ports: ['8080:8080']
    environment:
      SERVER_PORT: $SERVER_PORT
      SERVER_HOST: $SERVER_HOST
      SMTP_HOST: $SMTP_HOST
      SMTP_EMAIL: $SMTP_EMAIL
      SMTP_PASSWORD: $SMTP_PASSWORD
      SMTP_PORT: $SMTP_PORT
    volumes:
      - ./:/app
