// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: tinygomail/tiny_gomail.proto

package tinygomail

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body    string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Subject string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	From    string `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To      string `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *EmailMessage) Reset() {
	*x = EmailMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tinygomail_tiny_gomail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailMessage) ProtoMessage() {}

func (x *EmailMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tinygomail_tiny_gomail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailMessage.ProtoReflect.Descriptor instead.
func (*EmailMessage) Descriptor() ([]byte, []int) {
	return file_tinygomail_tiny_gomail_proto_rawDescGZIP(), []int{0}
}

func (x *EmailMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *EmailMessage) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *EmailMessage) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type SendResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tinygomail_tiny_gomail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tinygomail_tiny_gomail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_tinygomail_tiny_gomail_proto_rawDescGZIP(), []int{1}
}

func (x *SendResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_tinygomail_tiny_gomail_proto protoreflect.FileDescriptor

var file_tinygomail_tiny_gomail_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x74, 0x69, 0x6e, 0x79, 0x67, 0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x2f, 0x74, 0x69, 0x6e,
	0x79, 0x5f, 0x67, 0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x74, 0x69, 0x6e, 0x79, 0x67, 0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x60, 0x0a, 0x0c, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02,
	0x74, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x0c,
	0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x9a, 0x01, 0x0a, 0x0a, 0x54, 0x69, 0x6e, 0x79, 0x47,
	0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x45, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x65, 0x78,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x2e, 0x74, 0x69, 0x6e, 0x79, 0x67,
	0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x1a, 0x18, 0x2e, 0x74, 0x69, 0x6e, 0x79, 0x67, 0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x2e,
	0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0f,
	0x53, 0x65, 0x6e, 0x64, 0x48, 0x54, 0x4d, 0x4c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x18, 0x2e, 0x74, 0x69, 0x6e, 0x79, 0x67, 0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x18, 0x2e, 0x74, 0x69, 0x6e, 0x79,
	0x67, 0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x5f, 0x0a, 0x1e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x6d, 0x61, 0x78, 0x73, 0x68, 0x65, 0x6e, 0x64, 0x2e, 0x74, 0x69, 0x6e, 0x79, 0x67,
	0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x42, 0x0f, 0x54, 0x69, 0x6e, 0x79, 0x47, 0x6f, 0x6d, 0x61, 0x69,
	0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x78, 0x73, 0x68, 0x65, 0x6e, 0x64, 0x2f, 0x74, 0x69,
	0x6e, 0x79, 0x5f, 0x67, 0x6f, 0x6d, 0x61, 0x69, 0x6c, 0x2f, 0x74, 0x69, 0x6e, 0x79, 0x67, 0x6f,
	0x6d, 0x61, 0x69, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tinygomail_tiny_gomail_proto_rawDescOnce sync.Once
	file_tinygomail_tiny_gomail_proto_rawDescData = file_tinygomail_tiny_gomail_proto_rawDesc
)

func file_tinygomail_tiny_gomail_proto_rawDescGZIP() []byte {
	file_tinygomail_tiny_gomail_proto_rawDescOnce.Do(func() {
		file_tinygomail_tiny_gomail_proto_rawDescData = protoimpl.X.CompressGZIP(file_tinygomail_tiny_gomail_proto_rawDescData)
	})
	return file_tinygomail_tiny_gomail_proto_rawDescData
}

var file_tinygomail_tiny_gomail_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tinygomail_tiny_gomail_proto_goTypes = []interface{}{
	(*EmailMessage)(nil), // 0: tinygomail.EmailMessage
	(*SendResponse)(nil), // 1: tinygomail.SendResponse
}
var file_tinygomail_tiny_gomail_proto_depIdxs = []int32{
	0, // 0: tinygomail.TinyGomail.SendTextMessage:input_type -> tinygomail.EmailMessage
	0, // 1: tinygomail.TinyGomail.SendHTMLMessage:input_type -> tinygomail.EmailMessage
	1, // 2: tinygomail.TinyGomail.SendTextMessage:output_type -> tinygomail.SendResponse
	1, // 3: tinygomail.TinyGomail.SendHTMLMessage:output_type -> tinygomail.SendResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tinygomail_tiny_gomail_proto_init() }
func file_tinygomail_tiny_gomail_proto_init() {
	if File_tinygomail_tiny_gomail_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tinygomail_tiny_gomail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tinygomail_tiny_gomail_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tinygomail_tiny_gomail_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tinygomail_tiny_gomail_proto_goTypes,
		DependencyIndexes: file_tinygomail_tiny_gomail_proto_depIdxs,
		MessageInfos:      file_tinygomail_tiny_gomail_proto_msgTypes,
	}.Build()
	File_tinygomail_tiny_gomail_proto = out.File
	file_tinygomail_tiny_gomail_proto_rawDesc = nil
	file_tinygomail_tiny_gomail_proto_goTypes = nil
	file_tinygomail_tiny_gomail_proto_depIdxs = nil
}
